#!/bin/sh

# discover the distro that is being run
# [ $(< /etc/os-release) =~ artix ] && distro="artix"
# [ $(< /etc/os-release) =~ debian ] && distro="debian"
distro="artix"

# become root
if [ $distro="artix" ]; then
  # mark everything as dependencies
  doas pacman -D --asdeps $(pacman -Qet)
  # mark everything in the config file as explicitly installed
  # doas pacman -D --asexplicit $(cat /home/$USER/.config/packagepacman /home/$USER/.config/aurpackages | cut -d' ' -f1 | sed '/#/d') 
  doas pacman -D --asexplicit $(cat /home/$USER/.config/zlarbs/artix-pacman | cut -d' ' -f1 | sed '/#/d') 
  # remove the bloat
  doas pacman -Qdt | pacman -Rns -
fi
