#!/bin/sh
# this is essentually a remastering/improvment of luke smith's bookmarking script.
# this script gives you a list of bookmarked files. When one is selected, it will open the
# browser with that selection. basically a better bookmarking script. integrates well with
# the newbookmark script
# This only supports wayland and wlroots based compositors
# Written By GunslingerZach. (gunslingerzach.xyz)
grep -v '^#' ~/.local/share/zlarbs/emoji | tofi --prompt-text=emoji --horizontal=false --height=100% | cut -d' ' -f1 | wl-copy
[ $(wl-paste) = $(cat /dev/null) ] && exit
notify-send -t 3000 "copied "$(wl-paste)" to clipboard"
