#!/bin/sh

# A dmenu script for taking screenshots
case "$(printf "Fullscreen DP-3\nFullscreen DP-3 and edit\nFullscreen HDMI-A-1\nSelected Area" | dmenu -i -p 'Action: ')" in
  'Fullscreen DP-3') grim -o DP-3 $GRIM_DEFAULT_DIR/$(echo $(date +%s).png | dmenu -i -p "name?") ;;
  'Fullscreen DP-3 and edit') grim -o DP-3 - | swappy -f - ;;
  'Fullscreen HDMI-A-1') grim -o HDMI-A-1 $GRIM_DEFAULT_DIR/$(echo $(date +%s).png | dmenu -i -p "name?") ;;
	'Selected Area') grim -g "$(slurp)" $GRIM_DEFAULT_DIR/$(echo $(date +%s).png | dmenu -i -p "name?") ;;
	*) exit 1 ;;
esac
