#!/bin/sh

# A dmenu wrapper script for system functions.
export WM="sway"
case "$(readlink -f /sbin/init)" in
	*systemd*) ctl='systemctl' ;;
	*) ctl='loginctl' ;;
esac

wmpid(){ # This function is needed if there are multiple instances of the window manager.
	tree="$(pstree -ps $$)"
	tree="${tree#*$WM(}"
	echo "${tree%%)*}"
}

lock(){
    mpc pause
    pauseallmpv
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    swaylock
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
}

case "$(printf "💤 sleep\n🖥️shutdown\n🔃 reboot\n🔒 lock\n🚪 leave $WM\n🐻 hibernate" | tofi --prompt-text 'Action: ')" in
	'🔒 lock') swaylock -C $HOME/.config/sway/swaylock/config ;;
	"🚪 leave $WM") killall sway ;;
	'🐻 hibernate') swaylock -C $HOME/.config/sway/swaylock/config & $ctl hibernate -i ;;
	'💤 sleep') swaylock -C $HOME/.config/sway/swaylock/config & $ctl suspend ;;
	'🔃 reboot') $ctl reboot -i ;;
	'🖥️shutdown') $ctl poweroff -i ;;
	*) exit 1 ;;
esac
