(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(doom-font
   "-UKWN-Adwaita Mono-regular-normal-normal-*-13-*-*-*-m-0-iso10646-1")
 '(elfeed-feeds
   '("https://lettersfrommercia.substack.com/feed"
     "https://videos.lukesmith.xyz/feeds/videos.xml?videoChannelId=2"
     "https://lukesmith.xyz/index.xml" "https://www.archlinux.org/feeds/news/"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC_XaIjLffxy7dIheyKnErWg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCD1lODYlzMJ3YlZ30x2CwUg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC-FHoOa_jNSZy3IFctMEq2w"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCn_FAXem2-e3HQvmK-mOH4g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCRXnOs1rjfLMYrtZ-0n29NA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCcyjzeBeM6k5nEuzLlV78Hg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCqK_GSMbpiV8spgD3ZGloSw"
     "https://gunslingerzach.xyz/rss.xml"
     "https://gunslingerzach.xyz/microblog/rss.xml"
     "https://nitter.poast.org/NotGunslinger/rss"
     "https://stereophonic.space/users/GunslingerZach.rss"
     "https://poa.st/users/GunslingerZach/feed.atom"
     "https://vid.puffyan.us/feed/channel/UCu7K9lK3PfQZId6SelgzWBA"
     "https://odysee.com/$/rss/@Gunslinger-Zach:b"
     "https://www.sanjac.edu/rss.xml" "https://hamehura-anime.com/feed/"
     "https://blog.linuxmint.com/?feed=rss"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCh-kUCuC4cTAViXOBoegO1g"
     "https://www.themoneromoon.com/feed" "https://brave.com/feed"
     "https://odysee.com/$/rss/@LibertyDoll:e" "https://www.antiochian.org/feed"
     "https://nichegamer.com/feed/" "https://news.ycombinator.com/rss"
     "https://store.steampowered.com/feeds/news/collection/steam"
     "https://steamcommunity.com/games/1229490/rss/"
     "https://steamcommunity.com/games/1091500/rss/"
     "https://steamcommunity.com/games/1748620/rss/"
     "https://cryptobeat.substack.com/feed"
     "https://dannyduchamp.substack.com/feed"
     "https://acearchist.substack.com/feed"
     "https://auronmacintyre.substack.com/feed"
     "https://noumenovels.wordpress.com/feed/"
     "https://www.libsoftiktok.com/feed"
     "https://criticalzer0sequence.wordpress.com/feed/"
     "https://mises.org/feed/blog.rss" "https://c4ss.org/?feed=rss2"
     "https://statelesssovereignty.com/feed/" "https://biblethinker.org/feed/"
     "https://traditionalcatholicweeb.wordpress.com/feed/"
     "https://traditionalcatholicweeb.wordpress.com/category/anime-review/feed/"
     "https://www.hanshoppe.com/feed/" "https://www.stephankinsella.com/feed/"
     "https://blog.vaxry.net/feed" "https://denshi.org/rss.xml"
     "https://www.cozynet.org/feed/" "https://tfaz.xyz/rss.xml"
     "https://www.hoppean.org/?format=rss" "https://sadgrl.online/feed.xml"
     "http://lilibyte.net/nodes/rss/" "https://www.oca.org/reflections/feed"
     "https://pintswithaquinas.com/feed/"
     "https://xn--z7x.xn--6frz82g/blog/rss/"
     "https://jaxson.neocities.org/feed.xml" "https://www.piratewires.com/feed"
     "https://landchad.net/rss" "https://breakinginthehabit.org/feed/"
     "https://lindypress.net/rss" "https://thelinuxexp.com/feed.xml"
     "https://blog.alltheanime.com/feed/" "https://tuckercarlson.com/feed/"
     "https://ophanim.neocities.org/rss.xml" "https://mark.mcnally.je/blog/rss"
     "https://ericmurphy.xyz/index.xml" "https://bloatcat.tk/blog/index.xml"
     "https://blog.bugswriter.com/atom.xml" "https://yukinu.com/feed/rss.xml"
     "https://rss.nixnet.services/?action=display&bridge=XPathBridge&url=https%3A%2F%2Flainchan.org%2F%25CE%25A9%2Fres%2F70358.html&item=%2F%2F*%5B%40class%3D%22thread%22%5D%2F%2Fdiv%5B%40class%3D%22post+op%22+or+%40class%3D%22postcontainer%22%5D&title=%2F%2Fspan%5B%40class%3D%22subject%22%5D&content=.%2F%2F*%5B%40class%3D%22body%22%5D&uri=.%2F%2Fa%5B%40class%3D%22post_no%22%5D%2F%40href&author=.%2F%2Fspan%5B%40class%3D%22name%22%5D&timestamp=.%2F%2Ftime&enclosures=.%2F%2Fimg%5B%40class%3D%22post-image%22%5D&categories=%2F%2Fh1%5B%40class%3D%22glitch%22%5D&format=Atom"
     "https://odysee.com/$/rss/@AlphaNerd:8"
     "https://tilvids.com/feeds/videos.xml?videoChannelId=47"
     "https://odysee.com/$/rss/@DistroTube:2"
     "https://odysee.com/$/rss/@DenshiVideo:f"
     "https://denshi.live/feeds/videos.xml?videoChannelId=2"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCsnGwSIHyoYN0kiINAGUKxg"
     "https://odysee.com/$/rss/@BrodieRobertson:5"
     "https://odysee.com/$/rss/@NaomiBrockwell:4"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCeeFfhMcJa1kjtfZAGskOCA"
     "https://odysee.com/$/rss/@rossmanngroup:a"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC5KDiSAFxrDWhmysBcNqtMA"
     "https://bugswriter.com/videos.xml"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCs6KfncB4OV6Vug4o_bzijg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC8EYr_ArKMKaxfgRq-iCKzA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCXdERKqF1jDXH6pzWagz1DA"
     "https://notrelated.xyz/rss.xml"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCvySGkfy1W8fda287KMj2CA"
     "https://odysee.com/$/rss/@Repealthe20thCentury:3"
     "https://pintswithaquinas.libsyn.com/rss"
     "https://tomwoodsshow.libsyn.com/rss"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCEfe80CP2cs1eLRNQazffZw"
     "https://podcast.thelinuxexp.com/@tlenewspodcast/feed.xml"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCp4csaOD64mSzPxbfuzJcuA"
     "https://www.monerotalk.live/rss"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCu9TDs-dxsf5InzXY7Vkk6Q"
     "https://youtube.com/feeds/videos.xml?channel_id=UCd-qVRcjoK9zjtDs_LRxSmw"
     "https://youtube.com/feeds/videos.xml?channel_id=UCJiFgnnYpwlnadzTzhMnX_Q"
     "https://youtube.com/feeds/videos.xml?channel_id=UCxXqeNx2u6mLcFiPrX3-G_g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCFQMnBA3CS502aghlcr0_aw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCRcgy6GzDeccI7dkbbBna3Q"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCl_Pq-Qzv2Rxm3wGgYNvx5Q"
     "https://odysee.com/$/rss/@shink3n:4"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCUv20C_wy5FJe4FrUHlvz9g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCDcdVPVsJRxAVKq4vY0NYeg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCePbPbJ96WvMeMm_VuDkOJA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCbKdsXT-8ETLjTVHq6RlF_w"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCCdAuHh5MlTXQPxts1W9ICw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC7u2HaYBKDaLPcWmldxgGEA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC4VktB44EEkmQV8DymZVGtQ"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCrhLvfAHIZ2ET_F8AxRxXDw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC_cZXWB6T4WRXyTZiyH_LDw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCVfwlh9XpX2Y_tQfjeln9QA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCVFe7xhG6rl0ruoMQCJDtnw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC1okSIA8UEY8OqvtjGHFvzA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCzREuchzOqiawpEpvEM0Tyg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCMZXlVu8PM9jIGkJE2VpRGQ"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCTT_woATX1ily5aH-nZYkYg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCiLqiXa5O85APUBQV7X5w9Q"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC5qDet6sa6rODi7t6wfpg8g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCK7Bjrg4sFG6uw__5-S3Shg"
     "https://odysee.com/$/rss/@TheBabylonBee:7"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCYJAxrOiTRmgPSZrrZ9jL8g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCfZz8F37oSJ2rtcEJHM2kCg"
     "https://odysee.com/$/rss/@CareyWedler:f"
     "https://odysee.com/$/rss/@LiquidZulu:b"
     "https://odysee.com/$/rss/@MRHLegacy:8"
     "https://odysee.com/$/rss/@ShortFatOtaku:1"
     "https://odysee.com/$/rss/@CommonSenseSoapbox:a"
     "https://odysee.com/$/rss/@MentisWave:a"
     "https://youtube.com/feeds/videos.xml?channel_id=UCialsmUlTRABKPw31VDx1eQ"
     "https://odysee.com/$/rss/@SpringtimeofNations:f"
     "https://yewtu.be/feed/channel/UCvIgacgO3TH0Xgu92bFpCLg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCyUa016YoiY3cExu1mYDU6g"
     "https://youtube.com/feeds/videos.xml?channel_id=UC0aanx5rpr7D1M7KCFYzrLQ"
     "https://odysee.com/$/rss/@aydinpaladin:f5"
     "https://odysee.com/$/rss/@mises:1"
     "https://nitter.poast.org/TuckerCarlson/rss"
     "https://odysee.com/$/rss/@Disenthrall:8"
     "https://odysee.com/$/rss/@AwakenWithJP:9"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCd71KmJZ8mxKGCUDkdNqoWw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCHoRvL_JN1_pqRmMlgfUVsQ"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCR1D15p_vdP3HkrH8wgjQRw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCzfyYtgvkx5mLy8nlLlayYg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC3-IDlFc7J_HeKwcNfG0nLw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCwSNGPqXqpm8aN4rBaubwMw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCGwu0nbY2wSkW8N-cghnLpA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCdJdEguB1F1CiYe7OEi3SBg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCVhRMzNWYcg8XDTgB9NFRTw"
     "https://odysee.com/$/rss/@InternetHistorian:3"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC5VWF53rrEiuYvO5e5Ecn9Q"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC7Je57UJURMIx6lrXr3zO4g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC9T9mnA5u12DlQjeywuonpw"
     "https://odysee.com/$/rss/@samtime:1"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCfJxmjbygyA5KEdzzZv6Pbw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCchBatdUMZoMfJ3rIzgV84g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCmSp4bDxS9R0jpeZEvkut2g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCvCtIO1it51jSkZGibS9R3w"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC_vUfm0QoNfsfnuFc0xIrRg"
     "https://odysee.com/$/rss/@Kurosai:7"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCrVHlmiR7R5iZtn6zvkYLfg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCj4zC1Hfj-uc90FUXzRamNw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCuBpNon-yi4nJ1StjA1tSYA"
     "https://odysee.com/$/rss/@solidjj:3"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC2mP7il3YV7TxM_3m6U0bwA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCzj25NxFjI5jJM8StIBOvPA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC5qqBFOKTNAzIyE4g3SvuwQ"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCn4JrFLNPAXRd9Tpk7DcsLA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCIabPXjvT5BVTxRDPCBBOOQ"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UClyGlKOhDUooPJFy4v_mqPg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCCE5NVlm0FhbunMMBT48WAw"
     "https://odysee.com/$/rss/@SalC1:1"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCfgh3Ul_dG6plQ7rzuOLx-w"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCHZ986wm_sJT6wntdDTIIcw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCVWxjZ0nHFYNq7Iv7NiBvzQ"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC5p_l5ZeB_wGjO_yDXwiqvw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCgAyQyy6x3L-tmM1GICelGA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCAz5JW1_oryewk0eR-eP7Bw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCoqNvjhUxJRYW4JsT5fBK6w"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCrbA5a8z3E0Dm6hIiJRuL_w"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UClGMwdvf9Ftbh7EeB_t8n-g"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCuUm7Jx9g8NynC2pfhUmGfg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCUnaLtRXTH6tnh6MwtFVA1A"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCvt0HYxX34vUvqu66HLXeUw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC_GQ4mac4oN3wl1UdbFuTEA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCPQHf1fy4NjRYQ-Cr8ypWhg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCcnci5vbpLJ-rh_V9yXwawg"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCZi0oII2ua_I-fEnHdg3U2A"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCsS3UQD3nvoRkz_W5CR5Y-w"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCVAy9j7CKEFy2tyVn7yHPOA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC2W5RmbEJ0ZVVzSAw5UNWAQ"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCKx_4omANYTUlkqZc8k4emA"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCQ8Nk1VgyMgM7Mx3sX8WhPw"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC0dVpwGg7vd4fL65joRH54Q"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCT1ZkP03V18LmOj8zbyP-Dw"
     "https://odysee.com/$/rss/@romero_synth:5"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCL5ZlGtWoMkluPwuY-Wjv_Q"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UCoLmw-7YiyXJA6Ma0DvAzhg"
     "https://stonetoss.com/feed/"
     "https://spinster.xyz/users/TatsuyaIshida/feed.atom"
     "https://navyjoecomics.neocities.org/rss.xml"
     "https://monero.town/feeds/c/privacy.xml?sort=Active"
     "https://lemmy.ml/feeds/c/linux.xml?sort=Active"
     "https://www.reddit.com/r/linux.rss"
     "https://lemmy.ml/feeds/c/archlinux.xml?sort=Active"
     "https://www.reddit.com/r/archlinux.rss"
     "https://lemmy.ml/feeds/c/firefox.xml?sort=Active"
     "https://nixers.net/syndication.php"
     "https://www.reddit.com/r/hyprland.rss"
     "https://lemmy.ml/feeds/c/unixporn.xml?sort=Active"
     "https://www.reddit.com/r/unixporn.rss"
     "https://www.reddit.com/r/Monero.rss"
     "https://monero.town/feeds/c/monero.xml?sort=Active"
     "https://monero.town/feeds/c/moneromining.xml?sort=Active"
     "https://monero.town/feeds/c/monerojobs.xml?sort=Active"
     "https://monero.town/feeds/c/monerochan.xml?sort=Active"
     "https://monero.town/feeds/c/cakewallet.xml?sort=Active"
     "https://monero.town/feeds/c/moneromarket.xml?sort=Active"
     "https://nitter.poast.org/AltHistCody/rss"
     "https://nitter.poast.org/PerBylund/rss"
     "https://nitter.poast.org/AuronMacintyre/rss"
     "https://nitter.poast.org/AvietheDoram/rss"
     "https://web3isgoinggreat.com/feed.xml"
     "https://poa.st/users/Kettenkrad/feed.atom"
     "https://gleasonator.com/users/alex/feed.rss"
     "https://froth.zone/users/misato/feed.atom"
     "https://poa.st/users/oott/feed.atom"
     "https://nitter.poast.org/Tenkyu21/rss"
     "https://nitter.poast.org/Naze1940_Erica/rss"
     "https://nitter.poast.org/DailyTradAnime/rss"
     "https://nitter.poast.org/WaifuAesthetic/rss"
     "https://nitter.poast.org/daily_megumin/rss"
     "https://nitter.poast.org/hyxpk/rss"
     "https://nitter.poast.org/no_Hikari12/rss"
     "https://nitter.poast.org/nemuri1216/rss"
     "https://nitter.poast.org/not_katsu1/rss"
     "https://nitter.poast.org/KawaiAnimePics/rss"
     "https://nitter.poast.org/sakutakusakutan/rss"
     "https://nitter.poast.org/BunnyCunny1488/rss"
     "https://nitter.poast.org/CenturiiC/rss"
     "https://nitter.poast.org/DailyMegumin/rss"
     "https://github.com/LukeSmithxyz/voidrice/commits/master.atom"
     "https://github.com/hyprwm/Hyprland/releases.atom"
     "https://www.kernel.org/feeds/kdist.xml"
     "https://github.com/archlinux/linux/releases.atom"
     "https://www.getmonero.org/feed.xml"
     "https://betterthanadventure.tumblr.com/rss"
     "https://github.com/Turnip-Labs/ModMenu/releases.atom"
     "https://github.com/FarnGitHub/BTA-Dynamic-Light-Mod/releases.atom"
     "https://github.com/UselessBullets/BTA_Babric_LegacyUI/releases.atom"
     "https://github.com/rootEnginear/bta-bit-by-bit/releases.atom"
     "https://github.com/UselessBullets/BTA_Babric_PrismaticLibe/releases.atom"
     "https://github.com/Turnip-Labs/bta-halplibe/releases.atom"
     "https://github.com/Spicyfiction/Hardcore-Darkness-BTA-/releases.atom"
     "https://github.com/MartinSVK12/guidebookpp/releases.atom"
     "https://github.com/UselessBullets/bta-ironchests/releases.atom"
     "https://github.com/UselessBullets/BTA_Babric_ZoomPlus/releases.atom"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC8n7AzIQ0OLsWjmEdnahmeQ"
     "https://www.youtube.com/feeds/videos.xml?channel_id=UC5HEdXrvMyV24HE0c0LwO9Q")))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
