#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx='startx $XINITRC'
[ -f "$MBSYNCRC" ] && alias mbsync='mbsync -c $MBSYNCRC'

se() {
	choice="$(find ~/.config/scripts -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.config/scripts/$choice" ] && $EDITOR "$HOME/.config/scripts/$choice"
	}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	ytdlp="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="eza --icons --group-directories-first --no-quotes" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e='$EDITOR' \
	v='$EDITOR' \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref='shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutenvrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc'
# zach's additions
alias \
  sudo="doas" \
  sudoedit="doasedit" \
  waybar="waybar -c $HOME/.config/sway/waybar/config.jsonc -s $HOME/.config/sway/waybar/style.css" \
  bat="bat --color always --plain" \
  cat="bat --color always --plain" \
  neofetch="fastfetch -c $HOME/.config/fastfetch/neofetch.jsonc" \
  pfetch="fastfetch" \
  websync="rsync -rtvzP ~/documents/hugo/gunslingerzach/public/ gunslingerzach.xyz:/var/www/gunslingerzach/" \
  nb="newsboat" \
  wallpaper="nsxiv -t ~/pictures/wallpapers/*" \
  downview='eza $XDG_DOWNLOAD_DIR -f $HOME/downloads | fzf --height=100% | xargs -I{} xdg-open ~/downloads/{}' \
  fe='nvim $(fzf --preview="bat --plain --color=always {}")'
  # swayhide (only if you are running sway)
if [ $ZACH_DESKTOP="sway" ]; then 
    alias \
      hide="swayhide" \
      zathura="swayhide zathura" \
      mpv="swayhide mpv" \
      nsxiv="swayhide nsxiv"
fi
